(add-to-list 'load-path (concat global-load-path "/emms"))
(require 'emms-setup)
(emms-devel)
(emms-default-players)

;; emms-add-*, emms-play-*
;; (global-set-key (kbd "C-c a") 'emms-start)
;; (global-set-key (kbd "C-c s") 'emms-stop)
;; (global-set-key (kbd "C-c n") 'emms-next)
;; (global-set-key (kbd "C-c p") 'emms-previous)
;; (global-set-key (kbd "C-c r") 'emms-shuffle)
;; (global-set-key (kbd "C-c r") 'emms-random)
;; (global-set-key (kbd "C-c c") 'emms-pause)
;; (global-set-key (kbd "C-c b") 'emms-browser-add-tracks-and-play)
;; (global-set-key (kbd "C-c s") 'emms-smart-browse)
;; (global-set-key (kbd "<kp-left>") 'emms-seek)
;; (global-set-key (kbd "<kp-left>") 'emms-seek-backward)
;; (global-set-key (kbd "<kp-right>") 'emms-smart-forward)

;; (setq emms-show-format "Now playing: %s")
(add-hook 'emms-player-started-hook 'emms-show)
(add-hook 'emms-player-finished-hook 'emms-next-noerror)

;; (setq emms-source-file-default-directory "~/aleph0/music")

(require 'emms-mode-line)
(emms-mode-line 1)
(require 'emms-playing-time)
(emms-playing-time 1)

(require 'emms-player-mpd)
(setq emms-player-mpd-server-name "192.168.0.3")
(setq emms-player-mpd-server-port "6600")
(add-to-list 'emms-info-functions 'emms-info-mpd)
(add-to-list 'emms-player-list 'emms-player-mpd)
(setq emms-player-mpd-music-directory "~/music")
